apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-applications
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: applications/*
    repoURL: https://github.com/albmtez/argocd-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
