# kind: AppProject
# apiVersion: argoproj.io/v1alpha1
# metadata:
#   name: default
#   namespace: argocd
# spec:
#   clusterResourceWhitelist:
#   - group: '*'
#     kind: '*'
#   destinations:
#   - namespace: '*'
#     server: '*'
#   sourceRepos:
#   - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: apps/projects/default/
    repoURL: https://github.com/albmtez/argocd-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
