apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-project-one
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: project-one
  source:
    path: apps/projects/project-one
    repoURL: https://github.com/albmtez/argocd-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
